# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0baf33699d967b1af61a0e141fa683da7f2dbf0d2d10986010e76d732ab34abf7c6292ce30a707379075328f5392879dd2d73d1e388a4924a4277325a4171c8a

test:
  secret_key_base: f9c8c3794d713ef1931f464bea4f625b1153884c39d6bdc2a9a7dc3572c41fbfc67f4e2b332b355863f33f8b8191f9ccfa4b9d6b45a802e98949b09c2eef1c4f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
